apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 514684045883.dkr.ecr.us-east-1.amazonaws.com/my_mysql:my_db
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
  imagePullSecrets:
    - name: ecr-secret
